#!/usr/bin/env python
"""
Gym-V Temporal **image-only** → ``<state>`` schema rollouts.

Steps a Gym-V ``Temporal/<Title>-v0`` env (stable-retro / Genesis) and at
every step asks a vision LLM (GPT-5.5 by default) to convert the rendered
**game frame** into a canonical ``<state>…</state>`` schema. The env's
``obs.text`` is shipped as auxiliary context only — the image is the
PRIMARY input. The result is directly comparable to the text-head schema
generated by ``generate_gymv_text_schema.py``.

For each step we save:
  1. ``images/step_NNN.png``  — the visual state of the game env
  2. ``obs_text``              — the natural-language state from ``obs.text``
  3. ``schema_image_llm``      — schema produced by the vision (image) head
  4. ``heuristic_grounding``   — deterministic structured grounding from
                                 :func:`gymv_wrapper.build_temporal_visual_schema`

Output (``visual_grounding_tests/output/gymv_image/<env_id_safe>/<run_id>_ep<NNN>/``)::

    images/step_NNN.png
    steps.jsonl          — one JSON record per step
    run_summary.json     — timing/counts/model id

Usage (from ``Multi-hop-Reasoning-VLM-Agent`` or repo root on PYTHONPATH)::

    # One env, few steps, default model gpt-5.5
    export OPENAI_API_KEY=...
    python visual_grounding_tests/generate_gymv_image_schema.py \\
        --envs Temporal/Airstriker-v0 --episodes 1 --max_steps 3 -v

    # Dry run: no API; only env steps + heuristic grounding + frames
    python visual_grounding_tests/generate_gymv_image_schema.py --dry_run \\
        --envs Temporal/Airstriker-v0 --episodes 1 --max_steps 2

    # OpenRouter
    python visual_grounding_tests/generate_gymv_image_schema.py \\
        --model gpt-5.5 --base_url https://openrouter.ai/api/v1 \\
        --api_key "$OPENROUTER_API_KEY"
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import re
import sys
import time
import traceback
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

SCRIPT_DIR = Path(__file__).resolve().parent
CODEBASE_ROOT = SCRIPT_DIR.parent
if str(CODEBASE_ROOT) not in sys.path:
    sys.path.insert(0, str(CODEBASE_ROOT))

logger = logging.getLogger("gymv_image_schema")

DEFAULT_MODEL = os.environ.get("VLM_GYMV_IMAGE_MODEL", "gpt-5.5")
DEFAULT_MAX_TOKENS = int(os.environ.get("VLM_GYMV_IMAGE_MAX_TOKENS", "1200"))
DEFAULT_TEMPERATURE = float(os.environ.get("VLM_GYMV_IMAGE_TEMPERATURE", "0.2"))
DEFAULT_OUTPUT_TAG = "gymv_image"

_REASONING_TOKEN_MULTIPLIER = int(os.environ.get("VLM_GYMV_REASONING_MULT", "5"))
_REASONING_TOKEN_FLOOR = int(os.environ.get("VLM_GYMV_REASONING_FLOOR", "6000"))


# ── Lazy / optional imports ────────────────────────────────────────────

def _import_gymv_stack():
    """Import gym_v + per-game visual-grounding helpers (lazy: optional dep)."""
    import gym_v
    from gymv_wrapper.temporal_visual_grounding import (
        TEMPORAL_GAME_SPECS,
        build_temporal_visual_schema,
    )
    return gym_v, TEMPORAL_GAME_SPECS, build_temporal_visual_schema


def _import_schema_helpers():
    from vlm_wrapper.schema import (
        build_system_prompt,
        build_user_message,
        parse_schema_output,
        semantic_validate,
        validate_schema,
    )
    return {
        "build_system_prompt": build_system_prompt,
        "build_user_message": build_user_message,
        "parse_schema_output": parse_schema_output,
        "semantic_validate": semantic_validate,
        "validate_schema": validate_schema,
    }


def _import_api_func():
    try:
        from API_func import effective_openai_model, make_openai_client
        return make_openai_client, effective_openai_model
    except ImportError:
        return None, None


# ── ROM / env-id helpers ───────────────────────────────────────────────

def _rom_resolves(retro_game: str) -> bool:
    import stable_retro  # type: ignore

    try:
        stable_retro.data.get_romfile_path(retro_game)
        return True
    except (FileNotFoundError, OSError):
        if retro_game.endswith("-v0"):
            return False
        try:
            stable_retro.data.get_romfile_path(f"{retro_game}-v0")
            return True
        except (FileNotFoundError, OSError):
            return False


def _sanitize_env_id(env_id: str) -> str:
    return re.sub(r"[^\w\-.]+", "_", env_id)


# ── Image helpers ──────────────────────────────────────────────────────

def _to_pil(image: Any):
    try:
        from PIL import Image
    except ImportError:
        return None
    if image is None:
        return None
    if isinstance(image, list) and image:
        image = image[-1]
    if isinstance(image, Image.Image):
        return image.convert("RGB")
    try:
        arr = np.asarray(image)
    except Exception:
        return None
    if arr.ndim == 2:
        arr = np.stack([arr, arr, arr], axis=-1)
    if arr.dtype != np.uint8:
        if arr.size and float(arr.max()) <= 1.0:
            arr = (arr * 255.0).clip(0, 255).astype(np.uint8)
        else:
            arr = arr.astype(np.uint8)
    if arr.ndim == 3 and arr.shape[-1] == 4:
        arr = arr[..., :3]
    return Image.fromarray(arr, mode="RGB")


def _save_frame(image: Any, path: Path) -> Optional[str]:
    pil = _to_pil(image)
    if pil is None:
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        pil.save(str(path), format="PNG")
        return str(path)
    except Exception:
        return None


def _obs_image_size(obs: Any) -> Optional[Tuple[int, int]]:
    img = getattr(obs, "image", None)
    if img is None:
        return None
    if isinstance(img, list) and img:
        img = img[-1]
    try:
        w, h = img.size
        return (int(w), int(h))
    except Exception:
        return None


# ── OpenAI client + cross-model retry (gpt-5.x reasoning vs classic) ────

def _build_client_and_model(
    *, model: str, api_key: Optional[str], base_url: Optional[str],
):
    """Return ``(client, routed_model)`` or ``(None, model)`` on failure."""
    make_openai_client, effective_openai_model = _import_api_func()

    client: Any
    try:
        client = make_openai_client(api_key=api_key, base_url=base_url) if make_openai_client else None
    except Exception:
        client = None

    if client is None:
        try:
            import openai
            kw: Dict[str, Any] = {}
            if api_key:
                kw["api_key"] = api_key
            if base_url:
                kw["base_url"] = base_url
            client = openai.OpenAI(**kw) if (api_key or base_url) else openai.OpenAI()
        except Exception:
            return None, model

    if api_key or base_url:
        routed = model
    elif effective_openai_model is not None:
        try:
            routed = effective_openai_model(model)
        except Exception:
            routed = model
    else:
        routed = model
    return client, routed


def _chat_completion(
    client: Any,
    *,
    model: str,
    messages: List[Dict[str, Any]],
    temperature: float,
    max_tokens: int,
) -> str:
    """Call ``chat.completions.create`` with a cross-model retry shim.

    Reasoning models (gpt-5.x, o*) require ``max_completion_tokens`` and
    reject custom temperature; classic models accept the legacy names. We
    try the legacy names first and transparently retry once on the
    "Unsupported parameter" error path.
    """
    kwargs: Dict[str, Any] = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    try:
        resp = client.chat.completions.create(**kwargs)
        return resp.choices[0].message.content or ""
    except Exception as exc:  # noqa: BLE001
        msg = str(exc)
        needs_retry = (
            "max_completion_tokens" in msg
            or ("max_tokens" in msg and "Unsupported" in msg)
            or ("temperature" in msg and "Unsupported" in msg)
        )
        if not needs_retry:
            raise
        kwargs.pop("max_tokens", None)
        kwargs.pop("temperature", None)
        kwargs["max_completion_tokens"] = max(
            _REASONING_TOKEN_FLOOR,
            max_tokens * _REASONING_TOKEN_MULTIPLIER,
        )
        resp = client.chat.completions.create(**kwargs)
        return resp.choices[0].message.content or ""


# ── Schema validation wrapper ──────────────────────────────────────────

def _validate_schema(
    schema_text: Optional[str],
    *,
    image_size: Optional[Tuple[int, int]],
    helpers: Dict[str, Any],
) -> Tuple[List[str], Optional[Dict[str, Any]]]:
    if not schema_text:
        return [], None
    warnings = list(helpers["validate_schema"](schema_text))
    vres = helpers["semantic_validate"](
        schema_text, domain="gymv", image_size=image_size,
    )
    validation = vres.as_dict()
    warnings = warnings + list(vres.warnings) + list(vres.errors)
    return warnings, validation


# ── Image head: vision VLM (image + optional text) → schema ────────────

def generate_image_schema_llm(
    *,
    image: Any,
    obs_text: str,
    env_id: str,
    display_name: str,
    grounding_focus: str,
    task_id: str,
    goal: str,
    step: int,
    valid_actions: Optional[List[str]],
    helpers: Dict[str, Any],
    client: Any,
    routed_model: str,
    fallback_model: str,
    temperature: float,
    max_tokens: int,
    retries: int = 1,
    max_entities: int = 25,
) -> Dict[str, Any]:
    """Call the VLM with **image (+ optional text grounding)** to produce
    a ``<state>`` schema.

    The image is the primary input; ``obs.text`` is shipped as auxiliary
    context only. Reuses the same cross-domain ``vlm_wrapper.schema``
    system prompt as the text head so the two outputs are comparable.
    """
    pil = _to_pil(image)
    if pil is None:
        return {
            "schema": None,
            "raw": "Error: no image available",
            "warnings": ["no_image_for_visual_call"],
            "validation": None,
            "model": fallback_model,
            "model_routed": routed_model,
            "head": "image",
        }

    system = helpers["build_system_prompt"]("gymv", max_entities=max_entities)

    extra_parts: List[str] = []
    extra_parts.append(
        f"Game info: {display_name} ({env_id}). "
        f"Grounding focus: {grounding_focus or 'n/a'}."
    )
    if obs_text:
        extra_parts.append(
            f"Environment text state (auxiliary — for reference only):\n{obs_text}"
        )
    if valid_actions:
        extra_parts.append(
            "Valid actions for this environment (you MUST copy these "
            "strings verbatim into <actions>; do NOT rename or reformat):\n"
            + "\n".join(f"  - {a}" for a in valid_actions)
        )
    extra_context = "\n\n".join(extra_parts)

    user_content = helpers["build_user_message"](
        pil,
        domain="gymv",
        task_id=task_id,
        goal=goal,
        step=step,
        extra_context=extra_context,
    )
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": user_content},
    ]

    raw = ""
    schema = None
    for attempt in range(1, retries + 2):
        try:
            raw = _chat_completion(
                client,
                model=routed_model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
            )
            schema = helpers["parse_schema_output"](raw)
            if schema:
                break
            logger.warning("[image-VLM] attempt %d: no <state> block", attempt)
        except Exception as exc:  # noqa: BLE001
            logger.warning("[image-VLM] attempt %d failed: %s", attempt, exc)
            raw = f"Error: {exc!r}"

    warnings, validation = _validate_schema(
        schema, image_size=pil.size, helpers=helpers,
    )

    return {
        "schema": schema,
        "raw": raw,
        "warnings": warnings,
        "validation": validation,
        "model": fallback_model,
        "model_routed": routed_model,
        "image_size": list(pil.size),
        "head": "image",
    }


# ── Episode runner ─────────────────────────────────────────────────────

def run_one_episode(
    env_id: str,
    *,
    max_steps: int,
    out_dir: Path,
    model: str,
    temperature: float,
    max_tokens: int,
    dry_run: bool,
    api_key: Optional[str],
    base_url: Optional[str],
    verbose: bool,
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    gym_v, SPECS, build_temporal_visual_schema = _import_gymv_stack()
    helpers = _import_schema_helpers()

    if env_id not in SPECS:
        raise ValueError(f"Unknown Temporal env: {env_id}")
    if not _rom_resolves(SPECS[env_id].retro_game):
        raise FileNotFoundError(
            f"ROM not found for '{SPECS[env_id].retro_game}' — import it into stable-retro."
        )

    if dry_run:
        client, routed_model = None, model
    else:
        client, routed_model = _build_client_and_model(
            model=model, api_key=api_key, base_url=base_url,
        )
        if client is None:
            print(
                "[WARNING] No OpenAI/OpenRouter client could be built — "
                "set OPENAI_API_KEY / OPENROUTER_API_KEY, pass --api_key, "
                "or use --dry_run. Continuing with heuristic only."
            )

    images_dir = out_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)

    env = gym_v.make(env_id)
    odict, _ = env.reset()
    agent_id = next(iter(odict))
    obs = odict[agent_id]
    unwrapped = env.unwrapped
    description = ""
    if hasattr(unwrapped, "description"):
        description = getattr(unwrapped, "description", "") or ""
    goal_line = description.strip().split("\n")[0] if description else ""
    if not goal_line and env.spec is not None:
        goal_line = str(env.spec.id or env_id)

    spec = SPECS[env_id]
    records: List[Dict[str, Any]] = []
    total_reward = 0.0
    image_ok = image_err = 0
    t0 = time.time()

    for step in range(max_steps):
        img_size = _obs_image_size(obs)
        img_rel: Optional[str] = None
        pil = _to_pil(obs.image)
        if pil is not None:
            img_path = images_dir / f"step_{step:03d}.png"
            saved = _save_frame(pil, img_path)
            if saved:
                img_rel = str(img_path.relative_to(out_dir))

        valid_actions: Optional[List[str]] = None
        if obs.metadata and obs.metadata.get("available_actions"):
            valid_actions = [str(a) for a in obs.metadata["available_actions"]][:25]

        heuristic_grounding = build_temporal_visual_schema(env_id, obs)

        image_result: Optional[Dict[str, Any]] = None
        if not dry_run and client is not None:
            try:
                image_result = generate_image_schema_llm(
                    image=pil,
                    obs_text=obs.text or "",
                    env_id=env_id,
                    display_name=spec.display_name,
                    grounding_focus=spec.grounding_focus,
                    task_id=env_id,
                    goal=goal_line,
                    step=step,
                    valid_actions=valid_actions,
                    helpers=helpers,
                    client=client,
                    routed_model=routed_model,
                    fallback_model=model,
                    temperature=temperature,
                    max_tokens=max_tokens,
                )
                if image_result.get("schema"):
                    image_ok += 1
                else:
                    image_err += 1
            except Exception as exc:  # noqa: BLE001
                image_err += 1
                image_result = {
                    "schema": None,
                    "raw": f"Error: {exc!r}",
                    "warnings": [str(exc)],
                    "validation": None,
                    "model": model,
                    "head": "image",
                }
                if verbose:
                    traceback.print_exc()

        record: Dict[str, Any] = {
            "step": step,
            "env_id": env_id,
            "display_name": spec.display_name,
            "task_id": env_id,
            "image_path": img_rel,
            "image_size": list(img_size) if img_size else None,
            "obs_text": obs.text,
            "valid_actions": valid_actions,
            "heuristic_grounding": heuristic_grounding,
            "schema_image_llm": image_result,
            "model_scheduled": routed_model,
            "dry_run": dry_run,
        }
        records.append(record)

        if verbose:
            ok = bool(image_result and image_result.get("schema"))
            print(
                f"    step {step:>2}: image={'yes' if img_rel else 'no '} "
                f"vision_ok={'yes' if ok else 'no '}"
            )

        if step >= max_steps - 1:
            break

        odict, reward, terminated, truncated, _ = env.step({agent_id: "NOOP"})
        if isinstance(reward, dict):
            r = reward.get(agent_id, reward.get("__all__", 0.0))
        else:
            r = reward
        try:
            total_reward += float(r or 0.0)
        except (TypeError, ValueError):
            pass
        obs = odict[agent_id]
        term_all = bool(terminated.get("__all__", False)) if isinstance(terminated, dict) else bool(terminated)
        trunc_all = bool(truncated.get("__all__", False)) if isinstance(truncated, dict) else bool(truncated)
        if term_all or trunc_all:
            break

    try:
        env.close()
    except Exception:
        pass

    elapsed = time.time() - t0
    stats: Dict[str, Any] = {
        "env_id": env_id,
        "display_name": spec.display_name,
        "head": "image",
        "max_steps": max_steps,
        "steps_recorded": len(records),
        "total_reward": total_reward,
        "elapsed_seconds": round(elapsed, 3),
        "model": model,
        "model_routed": routed_model,
        "dry_run": dry_run,
        "image_schema_ok": image_ok,
        "image_schema_fail": image_err,
    }
    return records, stats


# ── CLI ────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Gym-V Temporal: vision frames → <state> schema (image-only VLM head)",
    )
    parser.add_argument(
        "--envs", type=str, nargs="+",
        default=["Temporal/Airstriker-v0"],
        help="Gym-V Temporal/* env ids (default: Airstriker)",
    )
    parser.add_argument("--episodes", type=int, default=1)
    parser.add_argument("--max_steps", type=int, default=3)
    parser.add_argument(
        "--model", type=str, default=DEFAULT_MODEL,
        help=f"VLM model id (default: {DEFAULT_MODEL}; env override: VLM_GYMV_IMAGE_MODEL).",
    )
    parser.add_argument("--temperature", type=float, default=DEFAULT_TEMPERATURE)
    parser.add_argument("--max_tokens", type=int, default=DEFAULT_MAX_TOKENS)
    parser.add_argument("--api_key", type=str, default=None)
    parser.add_argument("--base_url", type=str, default=None)
    parser.add_argument(
        "--dry_run", action="store_true",
        help="Skip API calls; only run env, save frames, and emit heuristic grounding.",
    )
    parser.add_argument("--output_dir", type=str, default=None)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO if args.verbose else logging.WARNING,
        format="%(levelname)s | %(name)s | %(message)s",
    )

    try:
        _import_gymv_stack()
    except ImportError as e:
        print(f"[FATAL] gym_v or gymv_wrapper not importable: {e}")
        sys.exit(1)

    from gymv_wrapper.temporal_visual_grounding import TEMPORAL_GAME_SPECS

    out_root = (
        Path(args.output_dir)
        if args.output_dir
        else SCRIPT_DIR / "output" / DEFAULT_OUTPUT_TAG
    )
    out_root.mkdir(parents=True, exist_ok=True)

    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    master: Dict[str, Any] = {
        "timestamp": datetime.now().isoformat(),
        "head": "image",
        "model": args.model,
        "dry_run": args.dry_run,
        "episodes_per_env": args.episodes,
        "max_steps": args.max_steps,
        "envs": args.envs,
    }
    all_summaries: List[Dict[str, Any]] = []

    for env_id in args.envs:
        if env_id not in TEMPORAL_GAME_SPECS:
            print(f"[SKIP] Unknown env (not in TEMPORAL_GAME_SPECS): {env_id}")
            continue
        if not _rom_resolves(TEMPORAL_GAME_SPECS[env_id].retro_game):
            print(
                f"[SKIP] {env_id}: ROM missing for "
                f"{TEMPORAL_GAME_SPECS[env_id].retro_game}"
            )
            continue

        safe = _sanitize_env_id(env_id)
        for ep in range(args.episodes):
            ep_dir = out_root / safe / f"{run_id}_ep{ep:03d}"
            ep_dir.mkdir(parents=True, exist_ok=True)
            print(f"\n  -> {env_id}  episode {ep + 1}/{args.episodes}  -> {ep_dir}")
            try:
                records, stats = run_one_episode(
                    env_id,
                    max_steps=args.max_steps,
                    out_dir=ep_dir,
                    model=args.model,
                    temperature=args.temperature,
                    max_tokens=args.max_tokens,
                    dry_run=args.dry_run,
                    api_key=args.api_key,
                    base_url=args.base_url,
                    verbose=args.verbose,
                )
                stats["episode"] = ep
                with open(ep_dir / "steps.jsonl", "w", encoding="utf-8") as f:
                    for r in records:
                        f.write(json.dumps(r, ensure_ascii=False, default=str) + "\n")
                with open(ep_dir / "run_summary.json", "w", encoding="utf-8") as f:
                    json.dump(stats, f, indent=2, ensure_ascii=False, default=str)
                print(
                    f"     wrote {len(records)} steps  "
                    f"image_ok={stats.get('image_schema_ok', 0)}"
                )
                all_summaries.append({**stats, "path": str(ep_dir)})
            except Exception as exc:  # noqa: BLE001
                print(f"  [ERROR] {env_id} ep{ep}: {exc}")
                traceback.print_exc()
                all_summaries.append(
                    {"env_id": env_id, "episode": ep, "error": str(exc)},
                )

    master["runs"] = all_summaries
    master_path = out_root / f"batch_{run_id}.json"
    with open(master_path, "w", encoding="utf-8") as f:
        json.dump(master, f, indent=2, ensure_ascii=False, default=str)
    print(f"\n  Batch summary: {master_path}")


if __name__ == "__main__":
    main()
