# Auto-generated by install/install_webarena_sites.sh on Wed Apr 29 05:48:24 UTC 2026
# Source this file to activate the WebArena URL endpoints, e.g.:
#   source /workspace/Multi-hop-Reasoning-VLM-Agent/cold_start/webarena_env.sh
# The actor pipeline launcher does this automatically when --tasks
# browsergym/webarena.* is passed.
export WA_HOMEPAGE="http://localhost:4399"
export WA_SHOPPING="http://localhost:7770"
export WA_SHOPPING_ADMIN="http://localhost:7780"
export WA_REDDIT="http://localhost:9999"
export WA_GITLAB="http://localhost:8023"
export WA_WIKIPEDIA="http://localhost:8888/viewer#wikipedia_en_all_maxi_2022-05/A/User:The_other_Kiwix_guy/Landing"
# Map is not auto-installed. Set WA_MAP after standing up your own
# OpenStreetMap + Nominatim + OSRM stack (see README), e.g.:
# export WA_MAP="http://<map-host>:3000"
export WA_MAP="${WA_MAP:-http://localhost:3000}"
