# Auto-generated by install/install_webshop.sh on Sun May  3 22:02:46 UTC 2026
# Source this file to point the bridge at the running WebShop server.
export WEBSHOP_DIR="/workspace/WebShop"
export WEBSHOP_BASE_URL="http://127.0.0.1:3000"
export WEBSHOP_HOST="127.0.0.1"
export WEBSHOP_PORT="3000"
export WEBSHOP_LITE="1"
