#!/usr/bin/env bash
# Create the isolated text-mode ALFWorld environment and download its data.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
YML="$SCRIPT_DIR/alfworld.environment.yml"

ENV_NAME="${ALFWORLD_ENV_NAME:-alfworld}"
DATA_DIR="${ALFWORLD_DATA:-$REPO_ROOT/.cache/alfworld_data}"
EXTRAS="${ALFWORLD_EXTRAS:-text}"
VERSION="${ALFWORLD_VERSION:-0.4.2}"
ENV_FILE="$REPO_ROOT/cold_start/alfworld_env.sh"

command -v conda >/dev/null 2>&1 || { echo "ERROR: conda not found"; exit 1; }
CONDA_BASE="$(conda info --base)"
source "$CONDA_BASE/etc/profile.d/conda.sh"

if ! conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; then
    conda env create -n "$ENV_NAME" -f "$YML"
fi
conda activate "$ENV_NAME"

COMMON_PIP_DEPS=(
    "spacy>=3.7,<3.8"
    "gymnasium>=0.28,<1.0"
    "numpy<2.0"
    "pyyaml>=6.0"
    "requests>=2.28"
    "httpx>=0.24"
    "openai>=1.0"
    "pydantic>=2.0,<3.0"
    "tqdm>=4.64"
)

case "$EXTRAS" in
    text) pip install "${COMMON_PIP_DEPS[@]}" "alfworld==${VERSION}" ;;
    vis|full) pip install "${COMMON_PIP_DEPS[@]}" "alfworld[${EXTRAS}]==${VERSION}" ;;
    *) echo "ERROR: ALFWORLD_EXTRAS must be text, vis, or full"; exit 1 ;;
esac

mkdir -p "$DATA_DIR"
export ALFWORLD_DATA="$DATA_DIR"
if [[ "${ALFWORLD_NO_DOWNLOAD:-0}" != "1" ]]; then
    alfworld-download
fi

{
    echo "# Generated by install/install_alfworld.sh"
    printf 'export ALFWORLD_DATA=%q\n' "$DATA_DIR"
    printf 'export ALFWORLD_ENV_NAME=%q\n' "$ENV_NAME"
    printf 'export PYTHONPATH=%q:${PYTHONPATH:-}\n' "$REPO_ROOT"
} > "$ENV_FILE"

python "$SCRIPT_DIR/alfworld_smoke.py"
echo "ALFWorld ready. Activate with: conda activate $ENV_NAME"
