"""Per-step vision-grounded ``<state>`` markup via the 35B multimodal judge.

T2.17 (2026-05-05): the actor's per-step prompt previously consumed a
deterministic Python-rendered ``<state>...</state>`` block (see
:mod:`trainer.coevolution._state_to_markup`).  Cold-start SFT data, by
contrast, was generated by GPT-5 looking at the *actual frame* using
the canonical :func:`vlm_wrapper.schema.build_system_prompt` /
:func:`build_user_message` prompts (see
``cold_start/generate_cold_start_actor_gymv.py`` lines ~725–755) — so
the SFT distribution carries visually-grounded entities (``player
ship``, ``enemy orb``, ``enemy shot``, ``cave wall``) while the live
training markup at the same step shows generic priors (``HUD bar``,
``score``, ``cave path``).  This distribution drift is one of the main
reasons the 9B actor under-performs Gemini / Qwen-VL teachers on the
same games.

This module closes the gap by calling the 35B judge (running with
``MULTIMODAL=1`` on port 8001) at every actor decision step with a
prompt that:

1. Embeds the canonical schema rules (gymv grid coordinates, ontology
   vocabulary, section ordering) lifted from
   :data:`vlm_wrapper.schema.SCHEMA_SPEC`.
2. Anchors the model on the SFT label distribution via real cold-start
   examples loaded from
   :func:`vlm_wrapper.few_shot_library.get_few_shot_examples` (when
   available) — these are the exact ``<state>...</state>`` blocks GPT-5
   produced during cold-start, so 35B has a concrete demo of the
   expected vocabulary / coordinate scheme.
3. Caps entities at 12 and uses placeholder labels in the schematic
   exemplar (so the model fills slots with frame content rather than
   regurgitating example labels — a verbatim-copy failure mode we
   observed when the only exemplar was a real TF3 trajectory).

We do NOT re-use the full ``build_system_prompt`` payload because the
35B (Qwen3.5-35B-A3B) follows the ~5 kB GPT-5 prompt unreliably — it
defaults to pixel-coordinates and produces duplicated entities.  The
trimmed prompt below keeps gymv grid coordinates and the SFT ontology
intact while staying small enough for 35B to follow consistently.

* **Same format contract** — ``<state>...<entities>...<attributes>...``
  block, parsable by the existing :func:`parse_schema_output` helper
  (and downstream :mod:`trainer.coevolution._state_to_markup`
  consumers, which tolerate partial markup defensively).
* **Same call shape** — synchronous ``str`` return value (the async
  variant just wraps a thread-pool / semaphore-bounded call).
* **Graceful degradation** — on any failure (judge offline, timeout,
  malformed output, missing frame) we silently return the deterministic
  ``state_to_markup`` output, so the training loop is never blocked by
  vision unavailability.

Hot-path safety
---------------
* **Concurrency cap** via :class:`asyncio.Semaphore` (default 12,
  matches the 35B's ``max_num_seqs=16`` minus headroom for the
  game-schema and harness-validator paths).
* **LRU cache** keyed on a SHA-1 hash of the data URL; identical frames
  (e.g. paused or repeated states) skip the LLM call entirely.
* **Hard timeout** (default 6 s) enforced via :func:`asyncio.wait_for` so
  a stuck judge can never wedge the rollout.
* **Optional frequency throttle** — call every N steps and reuse the
  prior markup in between (set
  ``vision_state_perception_every_n_steps > 1`` in config).

Output validation
-----------------
We perform a *minimal* well-formedness check (presence of opening
``<state>`` tag) before returning the LLM output.  We do NOT enforce
full schema validation here — downstream parsers handle malformed
markup defensively, and forcing strict validation would push edge cases
to the deterministic fallback unnecessarily.
"""

from __future__ import annotations

import asyncio
import hashlib
import logging
import os
import re
import time
from collections import OrderedDict
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


_CACHE_MAX_ENTRIES = 1024
# Raised 6.0 → 45.0 on 2026-05-20 (T2.17 follow-up).  Diagnostic on
# ``runs/gymv_airstriker_stage2_v3_20260521_011504``: production 35B
# vision-perception calls were taking ~11s/frame solo or 20-47s/frame
# under concurrency=12 contention, exceeding the old 6s timeout 100%
# of the time, silently falling back to the deterministic Python
# ``state_to_markup`` (HUD-blind, no player / enemy positions).  This
# mismatched the action_taking LoRA's SFT distribution and collapsed
# the agent's movement rate from teachers' 21-29% LEFT+RIGHT to 3%.
#
# 45s catches ~85% of the latency distribution (the slow tail comes
# from vLLM scheduling on the shared 35B); the remaining tail still
# falls back, but at a manageable rate (occasional vs every call).
_DEFAULT_TIMEOUT_S = 45.0
_DEFAULT_MAX_TOKENS = 2048
_DEFAULT_CONCURRENCY = 12
# T2.17b (2026-05-21): 0.1 → 0.0.  This is a *parser*-style task with
# strict format rules and only one structurally-correct answer per
# frame; greedy decoding gives more consistent formatting (fewer
# ``parse_failures``) and very-slightly faster tail latency on vLLM
# (no token-bucket sampling noise).
_DEFAULT_TEMPERATURE = 0.0
_MAX_RECENT_ACTIONS = 8

# Surface fallback failures every N events so silent DEBUG-only
# messages don't hide a misconfigured pipeline like the 6s timeout
# episode above.  Each bucket prints once per N events to avoid log
# flood while still being visible in launcher.log / coevolution.log.
_FALLBACK_WARN_EVERY_N = 50

# Lower than the cold-start cap (25) to keep the 35B's output focused
# on the most action-relevant entities and stay within max_tokens.
_SCHEMA_MAX_ENTITIES = 12

# Module-level singletons (lazy-init).
_semaphore: Optional[asyncio.Semaphore] = None
_cache: "OrderedDict[str, str]" = OrderedDict()
_stats: Dict[str, int] = {
    "calls": 0,
    "cache_hits": 0,
    "fallbacks": 0,
    "timeouts": 0,
    "parse_failures": 0,
    "build_failures": 0,
    "request_errors": 0,
}


# ── Public API ────────────────────────────────────────────────────────


async def vision_state_to_markup_async(
    *,
    obs_nl: str,
    info: Dict[str, Any],
    game: str,
    step: int,
    frame_data_url: Optional[str],
    fallback_markup: str,
    model: str,
    max_tokens: int = _DEFAULT_MAX_TOKENS,
    temperature: float = _DEFAULT_TEMPERATURE,
    timeout_s: float = _DEFAULT_TIMEOUT_S,
    concurrency: int = _DEFAULT_CONCURRENCY,
    executor: Any = None,
) -> str:
    """Render a vision-grounded ``<state>`` markup, with safe fallback.

    Parameters
    ----------
    obs_nl
        The natural-language observation string for this step.
    info
        Env ``info`` dict (used for action_names, score, structured_state).
    game
        Game / task identifier (e.g. ``gymv_thunder_force_iii``).
    step
        Zero-indexed env step.
    frame_data_url
        ``data:image/png;base64,...`` produced by ``SubprocessEnv.render()``
        or ``_encode_image_to_data_url(env.render())``.  When ``None`` the
        function short-circuits to ``fallback_markup`` (no LLM call).
    fallback_markup
        Deterministic ``state_to_markup`` output.  Returned on every
        failure path so the caller never sees a missing markup.
    model
        9B/35B vLLM model name (typically the 35B judge).
    max_tokens, temperature, timeout_s, concurrency
        Generation / dispatch knobs.  Defaults sized for the 35B running
        with ``max_num_seqs=16`` and ``MAX_MODEL_LEN=16384``.
    executor
        Optional ``ThreadPoolExecutor`` for the blocking OpenAI call.
        When ``None`` we use the running loop's default executor.

    Returns
    -------
    str
        Either a vision-grounded ``<state>...</state>`` block from the
        35B judge or the supplied ``fallback_markup``.
    """
    if not frame_data_url:
        return fallback_markup

    cache_key = _hash_url(frame_data_url)
    cached = _cache_get(cache_key)
    if cached is not None:
        _stats["cache_hits"] += 1
        return cached

    sem = _get_semaphore(concurrency)

    try:
        system_msg, user_content = _build_messages(
            obs_nl=obs_nl, info=info, game=game, step=step,
            frame_data_url=frame_data_url,
        )
    except Exception as exc:  # noqa: BLE001
        _stats["fallbacks"] += 1
        _stats["build_failures"] += 1
        _maybe_warn_fallback(
            "build_failures", game, step, timeout_s,
            f"prompt build failed: {exc!r}",
        )
        return fallback_markup

    loop = asyncio.get_event_loop()
    _stats["calls"] += 1

    async def _bounded_call() -> str:
        async with sem:
            return await loop.run_in_executor(
                executor,
                _ask_judge_blocking,
                system_msg, user_content, model, temperature, max_tokens,
            )

    try:
        raw = await asyncio.wait_for(_bounded_call(), timeout=timeout_s)
    except asyncio.TimeoutError:
        _stats["timeouts"] += 1
        _stats["fallbacks"] += 1
        _maybe_warn_fallback(
            "timeouts", game, step, timeout_s,
            f"timed out after {timeout_s:.0f}s — 35B judge too slow"
            f" (raise --vision-state-perception-timeout-s if persistent)",
        )
        return fallback_markup
    except Exception as exc:  # noqa: BLE001
        _stats["fallbacks"] += 1
        _stats["request_errors"] += 1
        _maybe_warn_fallback(
            "request_errors", game, step, timeout_s,
            f"request error: {exc!r}",
        )
        return fallback_markup

    markup = _extract_state_block(raw)
    if not markup:
        _stats["parse_failures"] += 1
        _stats["fallbacks"] += 1
        _maybe_warn_fallback(
            "parse_failures", game, step, timeout_s,
            f"parse failure on raw={raw[:200]!r}",
        )
        return fallback_markup

    _cache_put(cache_key, markup)
    return markup


def _maybe_warn_fallback(
    bucket: str, game: str, step: int, timeout_s: float, reason: str,
) -> None:
    """Surface fallback events at WARN every ``_FALLBACK_WARN_EVERY_N``.

    A purely DEBUG-only log line silently let the v3 run for 2.5 hours
    on 100% deterministic-fallback markup (timeout=6s vs 11s call
    time).  This helper makes each failure mode visible without
    flooding the log: the first event in each bucket is logged
    immediately, then once every N events thereafter.  Together with
    the explicit ``calls/timeouts/fallbacks/...`` stats counters in
    ``get_stats()``, this gives both immediate visibility and an
    aggregate diagnostic.
    """
    n = _stats.get(bucket, 0)
    if n == 1 or (n % _FALLBACK_WARN_EVERY_N == 0):
        logger.warning(
            "vision_state_perception[%s] event #%d (game=%s step=%d, "
            "timeout=%.0fs): %s; falling back to deterministic markup "
            "(cumulative fallbacks=%d / calls=%d)",
            bucket, n, game, step, timeout_s, reason,
            _stats.get("fallbacks", 0), _stats.get("calls", 0),
        )


def get_stats() -> Dict[str, int]:
    """Snapshot of call-site stats; useful for ``runs/.../trainer.log``."""
    return dict(_stats)


def reset_stats() -> None:
    """Reset stats counters (e.g. between phases)."""
    for k in _stats:
        _stats[k] = 0


# ── Prompt construction (matches cold-start SFT pipeline) ─────────────


_DOMAIN_BY_ENV: Dict[str, str] = {
    "gymv_temporal": "gymv",
    "gamingagent": "env_wrappers",  # tetris / candy_crush / 2048 share gymv schema
    "browsergym":  "browser",
    "alfworld":    "alfworld",
    "osworld":     "desktop",
    "orak":        "gymv",
}


def _resolve_domain(info: Dict[str, Any], game: str) -> str:
    """Map env_name → domain key understood by ``build_system_prompt``.

    Mirrors the routing in ``cold_start/generate_cold_start_actor_*``.
    Falls back to ``"gymv"`` when env_name is missing — gymv has the
    broadest entity vocabulary and is a safe default for retro games.
    """
    env_name = (info.get("env_name") or "").lower()
    if env_name in _DOMAIN_BY_ENV:
        return _DOMAIN_BY_ENV[env_name]
    if game.startswith("browsergym/"):
        return "browser"
    if env_name.startswith("gymv"):
        return "gymv"
    return "gymv"


def _data_url_to_pil(data_url: str) -> Any:
    """Decode a ``data:image/png;base64,...`` URL to a ``PIL.Image``.

    Imported lazily so the module is cheap to import in non-vision
    contexts (e.g. when running with ``--no-vision-state-perception``).
    """
    import base64 as _b64
    from io import BytesIO
    from PIL import Image

    payload = data_url.split("base64,", 1)[-1]
    return Image.open(BytesIO(_b64.b64decode(payload))).convert("RGB")


_SYSTEM_PROMPT = """\
You are a visual-state parser for a reinforcement-learning agent.
Look at the SUPPLIED FRAME and emit ONE ``<state>...</state>`` markup
block describing exactly what is shown in THIS frame, using the same
schema that the cold-start SFT data uses.

Critical rules:
  1. Output ONLY the ``<state>...</state>`` block.  No prose, no
     fenced code blocks, no extra whitespace before/after.
  2. ``pos=row,col,1,1`` — for gymv games this is GRID COORDINATES
     (NOT pixel coordinates).  Estimate row/col on a coarse 12-row
     by 16-col grid where (0,0) is the top-left of the frame.  Always
     emit four comma-separated integers: ``pos=8,13,1,1``.  Never
     pixel coords like ``pos=530,300,30,30``.
  3. ``type=`` MUST be one of: object, region, text, element.
  4. ``ontology=`` MUST be one of: textual_anchor, goal_indicator,
     interactive_entity, selectable_entity, tracked_entity,
     blocking_entity, container_entity, navigable_region.
  5. List 6–{max_entities} ENTITIES total.  Emphasise the agent's
     avatar (player/character), immediate threats, projectiles,
     pickups, on-screen text, and any blocking terrain.  When the
     same kind of object appears multiple times (e.g. a row of
     enemy projectiles, a wave of identical enemies), emit a SINGLE
     entity (e.g. ``enemy projectile wave``, ``enemy formation``)
     covering the cluster — do not enumerate individual instances.
  6. Ground every label in WHAT YOU ACTUALLY SEE.  Examples of good
     labels (drawn from the SFT cold-start distribution):
     ``player ship``, ``Strider``, ``slash arc``, ``enemy orb``,
     ``incoming bullet``, ``cave wall``, ``score hud``, ``health
     bars``, ``weapon pickup``, ``platform``.
  7. ``<targets>`` MUST set ``target=<player avatar id>``,
     ``blocker=<id of most pressing threat / obstacle or null>``,
     ``constraint=<one-line tactical priority>``,
     ``candidate_set=[<entity ids relevant to next action>]``.
  8. ``<actions>`` MUST list 4–6 actions copied verbatim from the
     ``available_actions`` list provided in the user message.  Do
     NOT invent action names.
  9. Use the supplied ``task=`` and ``domain=`` values verbatim.
"""


def _system_prompt(max_entities: int) -> str:
    return _SYSTEM_PROMPT.replace("{max_entities}", str(max_entities))


# ── Inference plan scaffold ──────────────────────────────────────────
# A reusable, game-agnostic chain-of-thought template that we drop into
# the **stable** portion of every visual-schema call (i.e. before the
# per-frame image).  Two goals:
#
#   1. Boost the cacheable prefix.  vLLM's prefix cache is broken the
#      moment image tokens appear; piling ~500 more tokens of stable
#      text in front of the image moves them inside the cached span.
#      Net: total cacheable prefix goes from
#      ``[system ~600]`` → ``[system ~600 + stable-user-text ~2500]``
#      across an entire run for a fixed (game, task) — i.e. ~4× the
#      cached tokens, freeing prompt-fill compute for the actually
#      novel image tokens.
#
#   2. Anchor model attention.  Explicit step-1/step-2/... scaffolds
#      consistently improve gymv-style entity recall in our SFT
#      labelling pipeline (same data the 35B was trained on).  This
#      gets us closer to the cold-start label distribution without
#      requiring any extra LoRA work.
#
# Kept abstract enough to apply to all gymv retro games (TF3,
# Strider, Centipede, Pac-Man, etc.) so the prefix stays stable across
# tasks within the same game family.  Per-task hints live in the
# 1-shot example, not here.
_INFERENCE_PLAN = """\
INFERENCE PLAN — apply these steps mentally before emitting <state>:

  Step 1. Locate the AGENT AVATAR (player ship / character / cursor).
          Record its approximate grid position (row, col) on the
          coarse 12×16 grid.
  Step 2. Identify the 1–3 NEAREST THREATS that block, shoot at, or
          could collide with the avatar within the next few frames.
          Cluster identical projectiles / enemies into a single
          ``... wave`` entity (do not enumerate).
  Step 3. Identify any PICKUPS, POWER-UPS, or score-bearing entities
          currently visible.
  Step 4. Note all on-screen TEXT HUD elements (score, level, life
          counter, weapon icon) — these go in as ``type=text``.
  Step 5. Choose ``target`` = avatar id, ``blocker`` = id of the most
          pressing threat / obstacle (or ``null`` if no immediate
          threat is in range).
  Step 6. Write ONE ``constraint=`` line that captures the immediate
          tactical priority (e.g. ``dodge incoming bullet``,
          ``intercept pickup before enemy``, ``advance right while
          shooting``).
  Step 7. Pick 4–6 ACTIONS from the supplied ``available_actions=``
          list that best execute the constraint.  Copy action names
          VERBATIM — never invent.

Output rule: emit ONLY the final ``<state>...</state>`` block; do
NOT include the plan itself or any preamble."""


def _load_few_shot_block(domain: str, task_id: str, n: int) -> str:
    """Return a rendered ``=== EXAMPLE i ===`` block, or empty string.

    Uses :func:`vlm_wrapper.few_shot_library.get_few_shot_examples`,
    the same loader the cold-start pipeline uses to anchor GPT-5 on
    the gold format.  Failures degrade silently to zero-shot.
    """
    if n <= 0:
        return ""
    try:
        from vlm_wrapper.few_shot_library import get_few_shot_examples
        examples = get_few_shot_examples(
            domain, n=n, task_id=task_id, fallback_domain="gymv",
        )
    except Exception:  # noqa: BLE001
        return ""
    if not examples:
        return ""
    blocks = []
    for i, ex in enumerate(examples, start=1):
        blocks.append(
            f"=== EXAMPLE {i} (a real cold-start <state> block) ===\n{ex}"
        )
    return "\n\n".join(blocks)


def _build_messages(
    *,
    obs_nl: str,
    info: Dict[str, Any],
    game: str,
    step: int,
    frame_data_url: str,
) -> tuple:
    """Return ``(system_str, user_content_list)`` for the OpenAI API.

    System prompt: focused gymv-style instructions (see
    :data:`_SYSTEM_PROMPT`) — small enough for the 35B to follow
    consistently, but anchored on the same grid-coord / ontology
    vocabulary the cold-start SFT pipeline uses.

    User message: ``image_url`` content part (so the vision tower
    sees the actual frame) + a text part with ``domain=`` /
    ``task=`` / ``goal=`` / ``available_actions=`` / ``recent_actions=`` /
    ``score_hint=``, plus 1 cold-start-format example loaded via
    :func:`get_few_shot_examples` to anchor the label distribution.
    """
    domain = _resolve_domain(info, game)

    action_names = info.get("action_names") or []
    if not action_names:
        ss = info.get("structured_state") or {}
        action_names = (
            (ss.get("control") or {}).get("available_actions") or []
        )
    action_names = [str(a) for a in action_names][:16]
    # T2.19g (2026-05-21): reorder by genre so the 35B's
    # ``available_actions=[…]`` list (which it copies verbatim into
    # its emitted ``<actions>`` block per inference-plan step 7) leads
    # with genre-relevant buttons.  ``_resolve_domain`` already gave us
    # the domain; pull genre off the structured_state when available.
    try:
        from trainer.coevolution.config import prioritise_actions
        _genre = ""
        _ss = info.get("structured_state") or {}
        if isinstance(_ss, dict):
            _genre = str(_ss.get("genre") or "")
        action_names = prioritise_actions(action_names, genre=_genre, game=game)
    except Exception:                                        # pragma: no cover
        pass

    ss = info.get("structured_state") or {}
    ram: Dict[str, Any] = {}
    score = ""
    if isinstance(ss, dict):
        ram = ss.get("ram_watch") or {}
        score = str(ram.get("score") or ss.get("score") or "").strip()

    recent = info.get("recent_actions") or []
    if isinstance(recent, list):
        recent = recent[-_MAX_RECENT_ACTIONS:]
    recent_str = ",".join(str(a) for a in recent) if recent else "none"

    task_id = (
        info.get("env_id")
        or info.get("game_name")
        or game
    )
    goal = (
        info.get("goal")
        or info.get("task")
        or f"Play {game.replace('_', ' ')} and maximise score."
    )

    # T2.17b (2026-05-21): bumped n=1 → n=2 after diagnosing that for
    # ``Temporal/Airstriker-v0`` the lookup was falling back to a single
    # *Strider* example in ``gymv.txt`` (the only file pre-2026-05-21),
    # giving the 35B a side-scrolling brawler prior when labeling a
    # vertical-scrolling shmup.  AS-specific cold-start examples now
    # live at ``gymv.Airstriker-v0.txt`` + ``.2.txt``; other games
    # still fall back to the gymv default until per-game files exist.
    fewshot = _load_few_shot_block(domain, str(task_id), n=2)

    actions_str = ",".join(action_names) if action_names else "stay"
    obs_compact = _truncate(obs_nl or "", 600)

    # ── Stable prefix: identical across every call within (game, task) ──
    # Layout: ``[stable-text] → [image] → [dynamic-text]``.  vLLM prefix
    # caching matches contiguous shared prefixes; putting the image
    # *first* destroyed cacheability because image tokens are unique
    # per frame, so cacheable text never appeared in the cached span.
    # Run ``tf3_coevo_20260515_042814`` confirmed the symptom: 35B
    # ``Prefix cache hit rate: 3.0%`` (= ~600 system tokens / ~20k
    # total = system prompt cached, everything else cold).  We can't
    # avoid the cut-off itself (image tokens are unique per frame) but
    # we can push the cut-off as late as possible by piling the
    # universal inference plan, 1-shot example, and task constants up
    # front.  Stable-prefix layers, longest-shared first:
    #
    #   [system prompt]              ~600 tok  ── all games / all tasks
    #   [INFERENCE PLAN scaffold]    ~500 tok  ── all gymv games
    #   [task-stable header]         ~200 tok  ── (game, task) constant
    #   [1-shot example]            ~1200 tok  ── (game, task) constant
    #   [closing instruction]        ~100 tok  ── all games
    #   ─────────────────────────────────────────────────────────
    #   total cacheable prefix     ~2600 tok  ── (vs. ~600 before)
    #   [image]                    ~1500 tok  ── per-frame, breaks cache
    #   [dynamic suffix]             ~80 tok  ── per-step, post-cache
    #
    # Net: cacheable prefix grows ~4×, prefix-cache hit rate should
    # climb from 3% to ~45-55% on a sustained single-game run, freeing
    # the bulk of the 35B's prompt-fill compute for the actually-novel
    # image tokens.
    stable_lines = [
        _INFERENCE_PLAN,
        "",
        # Task-stable header (constant across all calls of the same
        # (game, task) pair — entire TF3 run shares these exact lines).
        f"domain={domain}",
        f"task={task_id}",
        f"goal={str(goal)[:300]}",
        f"available_actions=[{actions_str}]",
    ]
    if fewshot:
        stable_lines.append("")
        stable_lines.append(fewshot)
    stable_lines.append("")
    stable_lines.append(
        "Look at the FRAME attached BELOW, mentally run the INFERENCE "
        "PLAN steps 1–7 above, then emit ONE ``<state>...</state>`` "
        "block for THIS frame only.  Replace the example's labels and "
        "positions with what you actually see in the frame; do NOT "
        "copy the example's labels verbatim unless they truly match."
    )
    stable_text = "\n".join(stable_lines)

    # ── Dynamic suffix: changes every step (never cacheable) ────────
    # Kept short so the post-image suffix is cheap to (re-)prefill.
    # Note: ``obs_text`` is truncated to 600 chars upstream — keep this
    # block under ~150 tokens total so the per-call recompute cost is
    # negligible relative to the image's ~1500 tokens.
    dynamic_lines = [
        f"step={step}",
        f"recent_actions=[{recent_str}]",
        f"score_hint={score or 'unknown'}",
    ]
    # Feed all ram_watch variables (lives, score, etc.) so the 35B can
    # cross-reference visual HUD elements against ground-truth RAM data.
    _ram_hints = {k: v for k, v in ram.items() if v is not None and k != "score"}
    if _ram_hints:
        _rh = ",".join(f"{k}={v}" for k, v in _ram_hints.items())
        dynamic_lines.append(f"ram_state=[{_rh}]")
    if obs_compact:
        dynamic_lines.append(f"obs_text={obs_compact}")
    dynamic_text = "\n".join(dynamic_lines)

    user_content = [
        {"type": "text", "text": stable_text},
        {"type": "image_url", "image_url": {"url": frame_data_url}},
        {"type": "text", "text": dynamic_text},
    ]
    return _system_prompt(_SCHEMA_MAX_ENTITIES), user_content


# ── 35B call (blocking; runs in executor) ─────────────────────────────


def _ask_judge_blocking(
    system_msg: str,
    user_content: List[Dict[str, Any]],
    model: str,
    temperature: float,
    max_tokens: int,
) -> str:
    """Synchronous OpenAI-compat call to the 35B judge.

    Uses the cold-start pipeline's two-message convention (system +
    user with multimodal content parts) so the 35B sees the same
    schema-spec preamble + image prompt the original SFT data was
    generated under.  Auth / URL-discovery is shared with
    :func:`trainer.coevolution._game_schema._ask_judge_multimodal`.
    """
    import openai  # local import keeps cold start cheap
    from API_func import (
        VLLM_API_KEY,
        _candidate_vllm_urls,
        _strip_think_tags,
    )

    candidate_urls = list(_candidate_vllm_urls(model))

    # Resolve the OpenRouter key from env var OR keys.py (via API_func).
    _or_key = (
        os.environ.get("OPENROUTER_API_KEY", "")
        or getattr(__import__("API_func"), "open_router_api_key", "")
    )
    _or_url = "https://openrouter.ai/api/v1"
    # Append OpenRouter as last-resort fallback so the 35B judge still
    # works when no local 35B vLLM instance is running.  The
    # ``_is_external`` branch below handles auth + max_tokens padding.
    if _or_key and _or_url not in candidate_urls:
        candidate_urls.append(_or_url)

    last_exc: Optional[Exception] = None
    for url in candidate_urls:
        _is_external = "openrouter.ai" in url or "api.openai.com" in url
        _api_key = (
            os.environ.get("OPENROUTER_API_KEY", "")
            or getattr(__import__("API_func"), "open_router_api_key", "")
        ) if _is_external else VLLM_API_KEY
        _model_id = model.lower() if _is_external else model
        try:
            # max_retries=0: the outer URL loop IS the retry mechanism.
            # Per-URL retries cause exponential backoff (0.5s+) and, on
            # non-HTTP ports (e.g. vLLM EngineCore :8001), the hanging
            # connection + retry accumulates zombie threads in the
            # executor, progressively starving the thread pool and
            # causing rollout times to grow per step.
            client = openai.OpenAI(
                base_url=url,
                api_key=_api_key,
                max_retries=0,
                timeout=5.0 if not _is_external else 30.0,
            )
            kwargs: Dict[str, Any] = dict(
                model=_model_id,
                messages=[
                    {"role": "system", "content": system_msg},
                    {"role": "user", "content": user_content},
                ],
                temperature=temperature,
                max_tokens=max_tokens,
            )
            if _is_external:
                # OpenRouter: even the non-thinking model variant may
                # emit a short <think> block that eats into max_tokens.
                # Budget 50% extra so the actual <state> output is
                # never truncated; _strip_think_tags removes the block.
                kwargs["max_tokens"] = int(max_tokens * 1.5)
            else:
                kwargs["extra_body"] = {
                    "chat_template_kwargs": {"enable_thinking": False},
                }
            response = client.chat.completions.create(**kwargs)
            raw = response.choices[0].message.content or ""
            return _strip_think_tags(raw)
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
            continue
    raise RuntimeError(
        f"All vLLM URLs failed for vision-perception call to {model!r}: "
        f"{last_exc}"
    )


# ── Output extraction / validation ────────────────────────────────────


_STATE_BLOCK_RE = re.compile(r"<state>.*?</state>", re.DOTALL)


def _extract_state_block(raw: str) -> Optional[str]:
    """Pull the first well-formed ``<state>...</state>`` from *raw*.

    Tries :func:`vlm_wrapper.schema.parse_schema_output` first (the
    canonical SFT-pipeline parser) so we accept exactly what cold-start
    accepts.  Falls back to a permissive regex with auto-close on
    truncation — the downstream :mod:`trainer.coevolution._state_to_markup`
    consumers tolerate partial markup defensively.
    """
    if not raw:
        return None
    try:
        from vlm_wrapper.schema import parse_schema_output
        parsed = parse_schema_output(raw)
        if parsed:
            if not parsed.strip().startswith("<state>"):
                parsed = "<state>\n" + parsed
            if "</state>" not in parsed:
                parsed = parsed.rstrip() + "\n</state>"
            return parsed
    except Exception:  # noqa: BLE001
        pass
    m = _STATE_BLOCK_RE.search(raw)
    if m:
        return m.group(0)
    if "<state>" in raw:
        body = raw[raw.index("<state>"):]
        if "</state>" not in body:
            body = body.rstrip() + "\n</state>"
        return body
    return None


# ── LRU cache helpers ─────────────────────────────────────────────────


def _hash_url(data_url: str) -> str:
    """16-hex-char SHA-1 of the base64 payload (post ``base64,`` marker)."""
    payload = data_url.split("base64,", 1)[-1]
    return hashlib.sha1(payload.encode("ascii", errors="ignore")).hexdigest()[:16]


def _cache_get(key: str) -> Optional[str]:
    if key in _cache:
        _cache.move_to_end(key)
        return _cache[key]
    return None


def _cache_put(key: str, value: str) -> None:
    _cache[key] = value
    _cache.move_to_end(key)
    while len(_cache) > _CACHE_MAX_ENTRIES:
        _cache.popitem(last=False)


def _get_semaphore(concurrency: int) -> asyncio.Semaphore:
    global _semaphore
    if _semaphore is None or getattr(_semaphore, "_value", -1) != concurrency:
        _semaphore = asyncio.Semaphore(max(1, int(concurrency)))
    return _semaphore


def _truncate(s: str, n: int) -> str:
    if len(s) <= n:
        return s
    return s[: n - 3] + "..."
